### ISSUE TITLE
Definir uma "chance máxima" para as perguntas

### ISSUE THREAD

**Issue by arthurgouveia** [sergiovilar/PHPinga#20]
Atualmente a maior parte de nossas perguntas possui apenas uma resposta correta, exigindo mais da galera e consequentemente tornando o jogo mais divertido, nem que seja só pra quem tá de fora.

Entretanto, uma das perguntas tem mais chance de acerto que de erro.

Proponho que a gente normalise algum "rate" pra isso, nem que seja no máximo ter 50% de acerto, mas pessoalmente acho que devia ser 20~30% de chance de acerto (1 em 3/4/5 alternativas é a correta).

**Comment by sergiopvilar** [comment]
Acho que 20%~50% é um rate bom.
