### ISSUE TITLE
Exibir a resposta correta caso o jogador erre a questão

### ISSUE THREAD

**Issue by nandomoreirame** [sergiovilar/PHPinga#21]
Seria legal se o sistema exibisse a resposta correta caso o jogador erre a questão, assim isso pode servir, não só como um game, mas como estudo também.

Eu fiquei meio assim quando joguei:

> Putz, errei! Mas qual era a certa?? Não mostrou, próxima pergunta.

Valeu! \o/

**Comment by arthurgouveia** [comment]
@nandomoreirame boa indagação, mas eu acho que a massa mesmo, por se tratar de um game pra embebedar a galera, era deixar a certa ainda sem expôr pra que o game demore mais tempo :D

**Comment by sergiopvilar** [comment]
É, concordo com @arthurgouveia porque atualmente quando vc erra uma pergunta ela volta pra a fila, daí outra pessoa pode pegar a mesma pergunta, isso prolonga mais o jogo :)

**Comment by arthurgouveia** [comment]
@abdala? Dá teu parecer que fechamos a issue, se concordar.

**Comment by abdala** [comment]
Como ferramenta de estudo faz sentido mostrar, mas como jogo acho interessante e concordo com o @sergiovilar e com vc, @arthurgouveia. Melhor não mostrar mesmo.

**Comment by arthurgouveia** [comment]
![Giphy](http://media0.giphy.com/media/tZF2erGJ5uOHe/giphy.gif)

**Comment by nandomoreirame** [comment]
hahahahahahahahaha valeu galera \o/
