### ISSUE TITLE
Randomizar ordem das respostas

### ISSUE THREAD

**Issue by arthurgouveia** [sergiovilar/PHPinga#4]
Só pra dar aquela embaralhada e complicar mais ainda a vida do bêbado e ele não ficar: não é a primeira, não é a segunda, então é a terceira.

**Comment by sergiopvilar** [comment]
Alguma sugestão @arthurgouveia? Hoje usamos o index no JSON pra dizer qual é a resposta correta. Talvez comparar o texto da resposta?

**Comment by arthurgouveia** [comment]
Acho que tirar a delegação do atributo "correta" e colocar essa responsabilidade na alternativa:

``` javascript
{
    question: 'Foo?',
    alternatives: [
      { text: 'Bar!', correct: true },
      { text: 'Mimimi!', correct: false },
      { text: 'Momomo!', correct: false }
    ]
  }
```

Assim dá pra fazer um shuffle no array e comparar se a alternativa escolhida é a que tem o `correct` como true.

Uma vez que o `alternatives` for randomizado, é só no `for` colocar como `value` do radio como um indice que quando enviado, pega o `alternatives[i].correct` e diz se é a certa ou não.

**Comment by sergiopvilar** [comment]
:+1:

**Comment by arthurgouveia** [comment]
#14 resolve essa issue.

**Comment by arthurgouveia** [comment]
Resolvido no merge do PR #14
